# Generated by Django 4.1.3 on 2022-12-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(db_index=True, default='Annonymus', max_length=200, verbose_name='Text'),
        ),
    ]
