# Generated by Django 4.1.3 on 2022-12-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='', upload_to='', verbose_name='File'),
        ),
    ]
