# Generated by Django 4.1.3 on 2022-12-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
